const EXERCISES_DATA = [
  {
    name: 'Приседания',
    emoji: '🦵',
    muscles: 'Ноги, ягодицы',
    sets: '3×15',
    desc: 'Ноги на ширине плеч, спина прямая. Опускайся до параллели бёдер с полом. Колени не выходят за носки.',
    calories_per_min: 6,
    difficulty: 1,
    category: 'strength',
    video: 'https://www.youtube.com/embed/YaXPRqUwItQ'
  },
  {
    name: 'Отжимания',
    emoji: '💪',
    muscles: 'Грудь, трицепс, плечи',
    sets: '3×10',
    desc: 'Руки чуть шире плеч, тело прямое от головы до пяток. Для начинающих — с колен. Опускайся до касания грудью пола.',
    calories_per_min: 7,
    difficulty: 2,
    category: 'strength',
    video: 'https://www.youtube.com/embed/wrLzBGDQ8yI'
  },
  {
    name: 'Планка',
    emoji: '🧘',
    muscles: 'Пресс, кор, плечи',
    sets: '3×30сек',
    desc: 'Упор на локти и носки, тело в одну линию. Не прогибай поясницу и не поднимай таз. Дыши ровно.',
    calories_per_min: 4,
    difficulty: 1,
    category: 'core',
    video: 'https://www.youtube.com/embed/TvxNkmjdhMM'
  },
  {
    name: 'Бёрпи',
    emoji: '🏃',
    muscles: 'Всё тело',
    sets: '3×8',
    desc: 'Присед → упор лёжа → отжимание → прыжок вверх. Самое мощное кардио-упражнение с собственным весом.',
    calories_per_min: 12,
    difficulty: 3,
    category: 'cardio',
    video: 'https://www.youtube.com/embed/auBLPXO8Fww'
  },
  {
    name: 'Скручивания',
    emoji: '🔄',
    muscles: 'Прямая мышца пресса',
    sets: '3×20',
    desc: 'Лёжа на спине, ноги согнуты, руки за головой. Поднимай лопатки от пола, напрягая пресс. Не тяни шею руками.',
    calories_per_min: 5,
    difficulty: 1,
    category: 'core',
    video: 'https://www.youtube.com/embed/5ER5Of4MOPI'
  },
  {
    name: 'Выпады',
    emoji: '🚶',
    muscles: 'Ноги, ягодицы',
    sets: '3×12/ногу',
    desc: 'Шаг вперёд, оба колена под 90°. Спина прямая, корпус вертикально. Чередуй ноги.',
    calories_per_min: 6,
    difficulty: 1,
    category: 'strength',
    video: 'https://www.youtube.com/embed/QOVaHnm-NlA'
  },
  {
    name: 'Подъём на носки',
    emoji: '🦶',
    muscles: 'Икроножные мышцы',
    sets: '3×20',
    desc: 'Встань на край ступеньки, поднимайся и опускайся на носках. Задерживайся в верхней точке на секунду.',
    calories_per_min: 3,
    difficulty: 1,
    category: 'strength',
    video: 'https://www.youtube.com/embed/gwLzBJYoWlI'
  },
  {
    name: 'Прыжки Джампинг Джек',
    emoji: '⭐',
    muscles: 'Всё тело, кардио',
    sets: '3×30сек',
    desc: 'Прыжки с одновременным разведением рук и ног в стороны. Отличная разминка и кардионагрузка.',
    calories_per_min: 8,
    difficulty: 1,
    category: 'cardio',
    video: 'https://www.youtube.com/embed/iSSAk4XCsRA'
  },
  {
    name: 'Велосипед (пресс)',
    emoji: '🚴',
    muscles: 'Косые мышцы пресса',
    sets: '3×15/стор',
    desc: 'Лёжа на спине крути воображаемые педали. Тянись локтем к противоположному колену, чередуя стороны.',
    calories_per_min: 5,
    difficulty: 2,
    category: 'core',
    video: 'https://www.youtube.com/embed/9FGilxCbdz8'
  },
  {
    name: 'Ягодичный мост',
    emoji: '🌉',
    muscles: 'Ягодицы, бицепс бедра',
    sets: '3×15',
    desc: 'Лёжа на спине, ноги согнуты, стопы на полу. Поднимай таз вверх, сжимая ягодицы в верхней точке.',
    calories_per_min: 4,
    difficulty: 1,
    category: 'strength',
    video: 'https://www.youtube.com/embed/OUgsJ8-Vi0E'
  },
  {
    name: 'Супермен',
    emoji: '🦸',
    muscles: 'Разгибатели спины, ягодицы',
    sets: '3×12',
    desc: 'Лёжа на животе, одновременно поднимай вытянутые руки и ноги. Задержись на 2 секунды в верхней точке.',
    calories_per_min: 4,
    difficulty: 1,
    category: 'core',
    video: 'https://www.youtube.com/embed/cc6UVRS7PaE'
  },
  {
    name: 'Прыжки с приседом',
    emoji: '🔥',
    muscles: 'Ноги, ягодицы, кардио',
    sets: '3×10',
    desc: 'Глубокий присед → мощный прыжок вверх → мягкое приземление на полусогнутые ноги. Руки помогают движению.',
    calories_per_min: 10,
    difficulty: 2,
    category: 'cardio',
    video: 'https://www.youtube.com/embed/A-cFYWvaHr0'
  },
  {
    name: 'Альпинист (скалолаз)',
    emoji: '⛰️',
    muscles: 'Кор, плечи, кардио',
    sets: '3×20',
    desc: 'В упоре лёжа поочерёдно подтягивай колени к груди в быстром темпе. Спина ровная, таз не поднимай.',
    calories_per_min: 10,
    difficulty: 2,
    category: 'cardio',
    video: 'https://www.youtube.com/embed/nmwgirgXLYM'
  },
  {
    name: 'Бег на месте с высоким подниманием колен',
    emoji: '🏃‍♂️',
    muscles: 'Ноги, кардио',
    sets: '3×30сек',
    desc: 'Бег на месте, поднимая колени выше уровня бёдер. Работай руками, держи корпус прямо.',
    calories_per_min: 9,
    difficulty: 1,
    category: 'cardio',
    video: 'https://www.youtube.com/embed/tx5rgpDAJRI'
  },
  {
    name: 'Стульчик у стены',
    emoji: '🪑',
    muscles: 'Квадрицепс, ягодицы',
    sets: '3×30сек',
    desc: 'Прижмись спиной к стене, присядь до угла 90° в коленях. Удерживай позицию. Руки свободно вдоль тела.',
    calories_per_min: 4,
    difficulty: 2,
    category: 'strength',
    video: 'https://www.youtube.com/embed/y-wV4Venusw'
  },
  {
    name: 'Обратные отжимания (трицепс)',
    emoji: '🔻',
    muscles: 'Трицепс, плечи',
    sets: '3×12',
    desc: 'Упор руками на скамью/стул сзади. Сгибай руки, опуская таз вниз, затем выжимай вверх. Ноги вытянуты.',
    calories_per_min: 5,
    difficulty: 2,
    category: 'strength',
    video: 'https://www.youtube.com/embed/0326dy_-CzM'
  },
  {
    name: 'Подъём ног лёжа',
    emoji: '🦿',
    muscles: 'Нижний пресс',
    sets: '3×15',
    desc: 'Лёжа на спине, руки вдоль тела. Поднимай прямые ноги до 90° и медленно опускай, не касаясь пола.',
    calories_per_min: 5,
    difficulty: 2,
    category: 'core',
    video: 'https://www.youtube.com/embed/JB2oyawG9KI'
  },
  {
    name: 'Русский твист',
    emoji: '🌀',
    muscles: 'Косые мышцы, кор',
    sets: '3×20',
    desc: 'Сидя с приподнятыми ногами, поворачивай корпус влево-вправо, касаясь руками пола. Спина под 45°.',
    calories_per_min: 5,
    difficulty: 2,
    category: 'core',
    video: 'https://www.youtube.com/embed/wkD8rjkodUI'
  },
  {
    name: 'Боковая планка',
    emoji: '📐',
    muscles: 'Косые мышцы, кор',
    sets: '3×20сек/стор',
    desc: 'Упор на один локоть, тело в одну линию. Удерживай положение. Бёдра не провисают. Повтори на другую сторону.',
    calories_per_min: 4,
    difficulty: 2,
    category: 'core',
    video: 'https://www.youtube.com/embed/K2VljzCC16g'
  },
  {
    name: 'Зашагивания на возвышение',
    emoji: '📦',
    muscles: 'Ноги, ягодицы',
    sets: '3×10/ногу',
    desc: 'Встань одной ногой на скамью/стул, поднимись за счёт рабочей ноги. Спина прямая, чередуй ноги.',
    calories_per_min: 7,
    difficulty: 2,
    category: 'strength',
    video: 'https://www.youtube.com/embed/dQqApCGd5Ss'
  },
  {
    name: 'Прыжки на тумбу',
    emoji: '🧱',
    muscles: 'Ноги, ягодицы, кардио',
    sets: '3×8',
    desc: 'Запрыгивай на устойчивую возвышенность двумя ногами. Приземляйся мягко, полностью выпрямляйся наверху.',
    calories_per_min: 10,
    difficulty: 3,
    category: 'cardio',
    video: 'https://www.youtube.com/embed/NBY9-kTuHEk'
  },
  {
    name: 'Становая тяга (без веса)',
    emoji: '🏋️',
    muscles: 'Спина, ягодицы, бицепс бедра',
    sets: '3×12',
    desc: 'Наклон вперёд с прямой спиной, руки скользят по ногам. Чувствуй растяжение задней поверхности бедра. Возвращайся напрягая ягодицы.',
    calories_per_min: 5,
    difficulty: 1,
    category: 'strength',
    video: 'https://www.youtube.com/embed/lJ3QwaXNJfw'
  },
  {
    name: 'Отжимания уголком (пайк)',
    emoji: '🔺',
    muscles: 'Плечи, трицепс',
    sets: '3×8',
    desc: 'Упор лёжа, таз поднят вверх буквой «Л». Сгибай руки, опуская голову к полу. Нагрузка на дельты.',
    calories_per_min: 6,
    difficulty: 3,
    category: 'strength',
    video: 'https://www.youtube.com/embed/sposDXWEB0A'
  },
  {
    name: 'Медвежья походка',
    emoji: '🐻',
    muscles: 'Всё тело, кор',
    sets: '3×10м',
    desc: 'На четвереньках, колени оторваны от пола. Двигайся вперёд, переставляя противоположные руку и ногу. Спина ровная.',
    calories_per_min: 8,
    difficulty: 2,
    category: 'cardio',
    video: 'https://www.youtube.com/embed/NLdasjEpnhA'
  },
  {
    name: 'Гусеница (инчворм)',
    emoji: '🐛',
    muscles: 'Кор, плечи, растяжка',
    sets: '3×8',
    desc: 'Из положения стоя наклонись, шагай руками вперёд до планки, затем шагай ногами к рукам и выпрямись.',
    calories_per_min: 6,
    difficulty: 2,
    category: 'stretch',
    video: 'https://www.youtube.com/embed/ZY2ji_Ho0dA'
  },
  {
    name: 'Ножницы (флаттер кик)',
    emoji: '✂️',
    muscles: 'Нижний пресс, бёдра',
    sets: '3×20',
    desc: 'Лёжа на спине, поднимай и опускай прямые ноги попеременно на 15-20 см от пола. Поясница прижата.',
    calories_per_min: 5,
    difficulty: 2,
    category: 'core',
    video: 'https://www.youtube.com/embed/ANVdMDaYRts'
  },
  {
    name: 'Тяга бедром (хип траст)',
    emoji: '🍑',
    muscles: 'Ягодицы, бицепс бедра',
    sets: '3×15',
    desc: 'Спина на скамье, стопы на полу. Поднимай таз вверх, максимально сжимая ягодицы. Задержись наверху.',
    calories_per_min: 5,
    difficulty: 2,
    category: 'strength',
    video: 'https://www.youtube.com/embed/SEdqd1n0icg'
  },
  {
    name: 'Ослиные удары (донки кик)',
    emoji: '🫏',
    muscles: 'Ягодицы',
    sets: '3×15/ногу',
    desc: 'На четвереньках поднимай согнутую ногу вверх, толкая пяткой в потолок. Сжимай ягодицу в верхней точке.',
    calories_per_min: 4,
    difficulty: 1,
    category: 'strength',
    video: 'https://www.youtube.com/embed/4YjLMdx3YZY'
  },
  {
    name: 'Пожарный гидрант',
    emoji: '🚒',
    muscles: 'Ягодицы, отводящие мышцы',
    sets: '3×15/ногу',
    desc: 'На четвереньках отводи согнутую ногу в сторону до уровня бедра. Корпус стабилен, не раскачивайся.',
    calories_per_min: 4,
    difficulty: 1,
    category: 'strength',
    video: 'https://www.youtube.com/embed/La3xzSBRRVE'
  },
  {
    name: 'Наклон вперёд стоя',
    emoji: '🙇',
    muscles: 'Задняя поверхность бедра, спина',
    sets: '3×30сек',
    desc: 'Стоя, ноги прямые, медленно наклоняйся вперёд, тянись руками к полу. Дыши спокойно, не пружинь.',
    calories_per_min: 2,
    difficulty: 1,
    category: 'stretch',
    video: 'https://www.youtube.com/embed/g-7ZWPCWv0U'
  },
  {
    name: 'Поза кобры',
    emoji: '🐍',
    muscles: 'Пресс, спина, грудь',
    sets: '3×20сек',
    desc: 'Лёжа на животе, выпрямляй руки, прогибая верхнюю часть спины. Таз на полу, плечи опущены. Раскрывай грудную клетку.',
    calories_per_min: 2,
    difficulty: 1,
    category: 'stretch',
    video: 'https://www.youtube.com/embed/JDcdhTuycOI'
  },
  {
    name: 'Поза собаки мордой вниз',
    emoji: '🐕',
    muscles: 'Плечи, спина, ноги',
    sets: '3×30сек',
    desc: 'Перевёрнутая буква «V»: ладони и стопы на полу, таз вверх. Тяни пятки к полу, спина прямая, голова между рук.',
    calories_per_min: 3,
    difficulty: 1,
    category: 'stretch',
    video: 'https://www.youtube.com/embed/EC7RGJ975iM'
  },
  {
    name: 'Поза воина I',
    emoji: '⚔️',
    muscles: 'Ноги, бёдра, баланс',
    sets: '3×20сек/стор',
    desc: 'Выпад вперёд, заднее колено прямое, руки вверх. Бёдра развёрнуты вперёд. Укрепляет ноги и улучшает баланс.',
    calories_per_min: 3,
    difficulty: 1,
    category: 'stretch',
    video: 'https://www.youtube.com/embed/k4qaVoAbeHM'
  },
  {
    name: 'Поза дерева',
    emoji: '🌳',
    muscles: 'Баланс, кор, ноги',
    sets: '3×30сек/стор',
    desc: 'Стоя на одной ноге, вторую стопу прижми к бедру. Руки над головой или перед грудью. Смотри в одну точку.',
    calories_per_min: 2,
    difficulty: 1,
    category: 'stretch',
    video: 'https://www.youtube.com/embed/wdln9qWYloU'
  },
  {
    name: 'Растяжка квадрицепса стоя',
    emoji: '🦵',
    muscles: 'Передняя поверхность бедра',
    sets: '3×20сек/ногу',
    desc: 'Стоя, согни ногу и подтяни пятку к ягодице рукой. Колени вместе, спина прямая. Придерживайся за опору при необходимости.',
    calories_per_min: 2,
    difficulty: 1,
    category: 'stretch',
    video: 'https://www.youtube.com/embed/Dbm7lNjEVgA'
  }
];
