const MOTIVATION_VIDEOS_DATA = [
  // === MOTIVATION (мотивация) — v1..v20 ===
  {id:'v1', title:'Никогда не сдавайся — мотивационная речь', src:'yt', url:'https://www.youtube.com/embed/ZXsQAXx_ao0', cat:'motivation'},
  {id:'v2', title:'Сила воли: как заставить себя действовать', src:'yt', url:'https://www.youtube.com/embed/mgmVOuLgFB0', cat:'motivation'},
  {id:'v3', title:'Ты можешь всё — мотивация на каждый день', src:'yt', url:'https://www.youtube.com/embed/g-jwWYX7Jlo', cat:'motivation'},
  {id:'v4', title:'Как перестать бояться и начать жить', src:'yt', url:'https://www.youtube.com/embed/iCvmsMzlF7o', cat:'motivation'},
  {id:'v5', title:'Мотивация которая изменит твою жизнь', src:'yt', url:'https://www.youtube.com/embed/kPtNON6Y31w', cat:'motivation'},
  {id:'v6', title:'Встань и иди к своей мечте', src:'yt', url:'https://www.youtube.com/embed/lsSC2vx7zFQ', cat:'motivation'},
  {id:'v7', title:'Речь которая заставит тебя действовать', src:'yt', url:'https://www.youtube.com/embed/5MgBikgcWnY', cat:'motivation'},
  {id:'v8', title:'Не жди идеального момента — действуй сейчас', src:'yt', url:'https://www.youtube.com/embed/TQMbvJNRpLE', cat:'motivation'},
  {id:'v9', title:'Как найти мотивацию когда ничего не хочется', src:'yt', url:'https://www.youtube.com/embed/UNQhuFL6CWg', cat:'motivation'},
  {id:'v10', title:'Путь к величию начинается с первого шага', src:'yt', url:'https://www.youtube.com/embed/y6Sxv-sUYtM', cat:'motivation'},
  {id:'v11', title:'Самая мощная мотивация для жизни', src:'yt', url:'https://www.youtube.com/embed/26U_seo0a1g', cat:'motivation'},
  {id:'v12', title:'Как стать лучшей версией себя', src:'yt', url:'https://www.youtube.com/embed/Y2jyjfcp1as', cat:'motivation'},
  {id:'v13', title:'Мотивация на успех — преодолей свои страхи', src:'yt', url:'https://www.youtube.com/embed/IdTMDpizis8', cat:'motivation'},
  {id:'v14', title:'Сделай невозможное возможным', src:'yt', url:'https://www.youtube.com/embed/hbkB_jNG-zE', cat:'motivation'},
  {id:'v15', title:'Почему ты ещё не добился успеха', src:'yt', url:'https://www.youtube.com/embed/3sK3wJAxGfs', cat:'motivation'},
  {id:'v16', title:'Верь в себя — мотивационное видео', src:'yt', url:'https://www.youtube.com/embed/v1rEP3Jiltc', cat:'motivation'},
  {id:'v17', title:'Боль временна — слава навсегда', src:'yt', url:'https://www.youtube.com/embed/mk82j1jQw_8', cat:'motivation'},
  {id:'v18', title:'Как мотивировать себя каждое утро', src:'yt', url:'https://www.youtube.com/embed/Lp7E973zozc', cat:'motivation'},
  {id:'v19', title:'Не позволяй никому украсть твою мечту', src:'yt', url:'https://www.youtube.com/embed/JC82Il2cjqA', cat:'motivation'},
  {id:'v20', title:'Секрет мотивации — начни с малого', src:'yt', url:'https://www.youtube.com/embed/rDjrOaoHz9s', cat:'motivation'},

  // === BUSINESS (бизнес) — v21..v40 ===
  {id:'v21', title:'Как построить успешный бизнес с нуля', src:'yt', url:'https://www.youtube.com/embed/Ihs4VFZWwn4', cat:'business'},
  {id:'v22', title:'10 правил успешного бизнеса', src:'yt', url:'https://www.youtube.com/embed/dBnpr3pkFlk', cat:'business'},
  {id:'v23', title:'Бизнес-секреты от миллиардеров', src:'yt', url:'https://www.youtube.com/embed/Gai06GYCoqc', cat:'business'},
  {id:'v24', title:'Как масштабировать бизнес: стратегии роста', src:'yt', url:'https://www.youtube.com/embed/jTYkdEU_B4o', cat:'business'},
  {id:'v25', title:'Ошибки начинающих предпринимателей', src:'yt', url:'https://www.youtube.com/embed/GlJMnDKjJKo', cat:'business'},
  {id:'v26', title:'Как создать бизнес-план за один день', src:'yt', url:'https://www.youtube.com/embed/Th8JoIan4dg', cat:'business'},
  {id:'v27', title:'Маркетинг для малого бизнеса', src:'yt', url:'https://www.youtube.com/embed/NqVY0gkG_1k', cat:'business'},
  {id:'v28', title:'Как найти свою нишу в бизнесе', src:'yt', url:'https://www.youtube.com/embed/F4K1PmQv0OI', cat:'business'},
  {id:'v29', title:'Управление командой: советы руководителю', src:'yt', url:'https://www.youtube.com/embed/RyTQ5-SQYTo', cat:'business'},
  {id:'v30', title:'Как привлечь первых клиентов', src:'yt', url:'https://www.youtube.com/embed/SimIev0m900', cat:'business'},
  {id:'v31', title:'Бизнес в интернете — с чего начать', src:'yt', url:'https://www.youtube.com/embed/qp0HIF3SfI4', cat:'business'},
  {id:'v32', title:'Как вести переговоры в бизнесе', src:'yt', url:'https://www.youtube.com/embed/HAnw168huqA', cat:'business'},
  {id:'v33', title:'Секреты успешных продаж', src:'yt', url:'https://www.youtube.com/embed/llKvV8_T95M', cat:'business'},
  {id:'v34', title:'Как автоматизировать бизнес-процессы', src:'yt', url:'https://www.youtube.com/embed/YQs6IC-vgmo', cat:'business'},
  {id:'v35', title:'Стартап: от идеи до реализации', src:'yt', url:'https://www.youtube.com/embed/wvVPdyYeaQU', cat:'business'},
  {id:'v36', title:'Как выйти из операционки бизнеса', src:'yt', url:'https://www.youtube.com/embed/UF8uR6Z6KLc', cat:'business'},
  {id:'v37', title:'Партнёрство в бизнесе: плюсы и минусы', src:'yt', url:'https://www.youtube.com/embed/AyOqGRjVtls', cat:'business'},
  {id:'v38', title:'Как создать личный бренд', src:'yt', url:'https://www.youtube.com/embed/KEYbGWoLSuE', cat:'business'},
  {id:'v39', title:'Бизнес-модели которые работают', src:'yt', url:'https://www.youtube.com/embed/QoAOzMTLP5s', cat:'business'},
  {id:'v40', title:'Как принимать сложные решения в бизнесе', src:'yt', url:'https://www.youtube.com/embed/PY9DcIMGxMs', cat:'business'},

  // === FINANCE (финансы) — v41..v60 ===
  {id:'v41', title:'Финансовая грамотность: основы для каждого', src:'yt', url:'https://www.youtube.com/embed/PHe0bXAIuk0', cat:'finance'},
  {id:'v42', title:'Как начать инвестировать с нуля', src:'yt', url:'https://www.youtube.com/embed/gFQNPmLKj1k', cat:'finance'},
  {id:'v43', title:'Пассивный доход: 7 источников заработка', src:'yt', url:'https://www.youtube.com/embed/M5y69v1RbU0', cat:'finance'},
  {id:'v44', title:'Как копить деньги правильно', src:'yt', url:'https://www.youtube.com/embed/HQzonm0zYgI', cat:'finance'},
  {id:'v45', title:'Инвестиции в акции для начинающих', src:'yt', url:'https://www.youtube.com/embed/p7HKvqRI_Bo', cat:'finance'},
  {id:'v46', title:'Как выбраться из долгов навсегда', src:'yt', url:'https://www.youtube.com/embed/HCqiKMBOxWU', cat:'finance'},
  {id:'v47', title:'Секреты богатых людей — финансовые привычки', src:'yt', url:'https://www.youtube.com/embed/T4VlSiaj9Wc', cat:'finance'},
  {id:'v48', title:'Как составить личный бюджет', src:'yt', url:'https://www.youtube.com/embed/sVKQn2I4HDM', cat:'finance'},
  {id:'v49', title:'Криптовалюта: стоит ли инвестировать', src:'yt', url:'https://www.youtube.com/embed/kubGCSj5y3k', cat:'finance'},
  {id:'v50', title:'Как создать финансовую подушку безопасности', src:'yt', url:'https://www.youtube.com/embed/ecqUXj-Dw90', cat:'finance'},
  {id:'v51', title:'Недвижимость как инвестиция', src:'yt', url:'https://www.youtube.com/embed/z0sE3LoyGqQ', cat:'finance'},
  {id:'v52', title:'Как увеличить доход в два раза', src:'yt', url:'https://www.youtube.com/embed/M1CHPnZfFmU', cat:'finance'},
  {id:'v53', title:'Финансовая свобода — пошаговый план', src:'yt', url:'https://www.youtube.com/embed/pLACid9IL3I', cat:'finance'},
  {id:'v54', title:'Ошибки в управлении деньгами', src:'yt', url:'https://www.youtube.com/embed/Ei-P_pVBmQI', cat:'finance'},
  {id:'v55', title:'Как работают сложные проценты', src:'yt', url:'https://www.youtube.com/embed/wf91rEGw88Q', cat:'finance'},
  {id:'v56', title:'ETF фонды простыми словами', src:'yt', url:'https://www.youtube.com/embed/OwpFBi2mOno', cat:'finance'},
  {id:'v57', title:'Как перестать тратить деньги впустую', src:'yt', url:'https://www.youtube.com/embed/kZA9Hnp3aV4', cat:'finance'},
  {id:'v58', title:'Налоги для физических лиц — что нужно знать', src:'yt', url:'https://www.youtube.com/embed/GwMxUbBNdUQ', cat:'finance'},
  {id:'v59', title:'Диверсификация портфеля: зачем и как', src:'yt', url:'https://www.youtube.com/embed/Wv0pJh8mFk0', cat:'finance'},
  {id:'v60', title:'Мышление богатого человека', src:'yt', url:'https://www.youtube.com/embed/CnD2VFaEVS0', cat:'finance'},

  // === ENTREPRENEURSHIP (предпринимательство) — v61..v80 ===
  {id:'v61', title:'Как стать предпринимателем: первые шаги', src:'yt', url:'https://www.youtube.com/embed/ZoqgAy3h4OM', cat:'entrepreneurship'},
  {id:'v62', title:'История успеха: от нуля до миллиона', src:'yt', url:'https://www.youtube.com/embed/8ZhoeSaPF-k', cat:'entrepreneurship'},
  {id:'v63', title:'Как найти бизнес-идею', src:'yt', url:'https://www.youtube.com/embed/MJnTavFvluk', cat:'entrepreneurship'},
  {id:'v64', title:'Предпринимательское мышление', src:'yt', url:'https://www.youtube.com/embed/uvHwyrem0LQ', cat:'entrepreneurship'},
  {id:'v65', title:'Как начать бизнес без денег', src:'yt', url:'https://www.youtube.com/embed/wlkJb1u_F_0', cat:'entrepreneurship'},
  {id:'v66', title:'Риски в предпринимательстве и как их снизить', src:'yt', url:'https://www.youtube.com/embed/QRZ_l7cVzzU', cat:'entrepreneurship'},
  {id:'v67', title:'Как привлечь инвестиции в стартап', src:'yt', url:'https://www.youtube.com/embed/RfWgVWGEuGE', cat:'entrepreneurship'},
  {id:'v68', title:'Предприниматель vs наёмный работник', src:'yt', url:'https://www.youtube.com/embed/nKIbRCGEj4c', cat:'entrepreneurship'},
  {id:'v69', title:'Как создать MVP продукта', src:'yt', url:'https://www.youtube.com/embed/xPJoq_QVsY4', cat:'entrepreneurship'},
  {id:'v70', title:'Истории провалов великих предпринимателей', src:'yt', url:'https://www.youtube.com/embed/zLYECIjmnQs', cat:'entrepreneurship'},
  {id:'v71', title:'Как собрать команду мечты', src:'yt', url:'https://www.youtube.com/embed/ojz25lOa9QI', cat:'entrepreneurship'},
  {id:'v72', title:'Франшиза: стоит ли покупать', src:'yt', url:'https://www.youtube.com/embed/UC1mr4nmSbY', cat:'entrepreneurship'},
  {id:'v73', title:'Как выйти на международный рынок', src:'yt', url:'https://www.youtube.com/embed/KvDAGROSqWo', cat:'entrepreneurship'},
  {id:'v74', title:'Ошибки первого года бизнеса', src:'yt', url:'https://www.youtube.com/embed/1k5MshztfMg', cat:'entrepreneurship'},
  {id:'v75', title:'Как создать уникальное торговое предложение', src:'yt', url:'https://www.youtube.com/embed/FWXneQYlPbk', cat:'entrepreneurship'},
  {id:'v76', title:'Масштабирование стартапа: пошагово', src:'yt', url:'https://www.youtube.com/embed/DePKAS8GYpM', cat:'entrepreneurship'},
  {id:'v77', title:'Нетворкинг для предпринимателей', src:'yt', url:'https://www.youtube.com/embed/0JINsnqRsEc', cat:'entrepreneurship'},
  {id:'v78', title:'Как получить грант на бизнес', src:'yt', url:'https://www.youtube.com/embed/1hTcMAl3AA0', cat:'entrepreneurship'},
  {id:'v79', title:'Социальное предпринимательство', src:'yt', url:'https://www.youtube.com/embed/C5FGyOqxOcU', cat:'entrepreneurship'},
  {id:'v80', title:'Как продать бизнес по максимальной цене', src:'yt', url:'https://www.youtube.com/embed/oP29k3gEsiU', cat:'entrepreneurship'},

  // === DISCIPLINE (дисциплина) — v81..v100 ===
  {id:'v81', title:'Как развить самодисциплину за 30 дней', src:'yt', url:'https://www.youtube.com/embed/IlU-zDU6aQ0', cat:'discipline'},
  {id:'v82', title:'Утренние привычки успешных людей', src:'yt', url:'https://www.youtube.com/embed/H6ZZBGo6sHk', cat:'discipline'},
  {id:'v83', title:'Как перестать лениться и начать действовать', src:'yt', url:'https://www.youtube.com/embed/W8e_tAEM80k', cat:'discipline'},
  {id:'v84', title:'Правило 5 секунд — Мел Роббинс', src:'yt', url:'https://www.youtube.com/embed/nhnQbxAe7cU', cat:'discipline'},
  {id:'v85', title:'Как создать продуктивный распорядок дня', src:'yt', url:'https://www.youtube.com/embed/2paoNvG5Nmo', cat:'discipline'},
  {id:'v86', title:'Сила привычки — как изменить жизнь', src:'yt', url:'https://www.youtube.com/embed/W1eYrhGeffc', cat:'discipline'},
  {id:'v87', title:'Как побороть прокрастинацию навсегда', src:'yt', url:'https://www.youtube.com/embed/arj7oStGLkU', cat:'discipline'},
  {id:'v88', title:'Дисциплина важнее мотивации', src:'yt', url:'https://www.youtube.com/embed/IX51JMQqSZ0', cat:'discipline'},
  {id:'v89', title:'Как встать рано утром и быть продуктивным', src:'yt', url:'https://www.youtube.com/embed/PZ7lDrwYdZc', cat:'discipline'},
  {id:'v90', title:'Тайм-менеджмент: как всё успевать', src:'yt', url:'https://www.youtube.com/embed/oTugjssqOT0', cat:'discipline'},
  {id:'v91', title:'Как выработать силу воли', src:'yt', url:'https://www.youtube.com/embed/k2Wcu6aGyz8', cat:'discipline'},
  {id:'v92', title:'Метод помидора для продуктивности', src:'yt', url:'https://www.youtube.com/embed/H0k0TQfZGSc', cat:'discipline'},
  {id:'v93', title:'Как избавиться от вредных привычек', src:'yt', url:'https://www.youtube.com/embed/W_fkicNVR4Y', cat:'discipline'},
  {id:'v94', title:'Минимализм как путь к продуктивности', src:'yt', url:'https://www.youtube.com/embed/GgBpyNsS-jU', cat:'discipline'},
  {id:'v95', title:'Как фокусироваться на важном', src:'yt', url:'https://www.youtube.com/embed/Hu4Yvq-g7_Y', cat:'discipline'},
  {id:'v96', title:'Атомные привычки — ключевые идеи', src:'yt', url:'https://www.youtube.com/embed/YT7tQzmGRLA', cat:'discipline'},
  {id:'v97', title:'Как работать когда не хочется', src:'yt', url:'https://www.youtube.com/embed/vJG698U2Mvo', cat:'discipline'},
  {id:'v98', title:'Медитация для концентрации и спокойствия', src:'yt', url:'https://www.youtube.com/embed/inpok4MKVLM', cat:'discipline'},
  {id:'v99', title:'Как перестать отвлекаться на телефон', src:'yt', url:'https://www.youtube.com/embed/VpHyLG-sc4g', cat:'discipline'},
  {id:'v100', title:'Ежедневные ритуалы для самодисциплины', src:'yt', url:'https://www.youtube.com/embed/t1hoOwbfgME', cat:'discipline'},

  // === SPORT (спорт) — v101..v120 ===
  {id:'v101', title:'Мотивация для тренировок — не сдавайся', src:'yt', url:'https://www.youtube.com/embed/hV63DbQ_qSc', cat:'sport'},
  {id:'v102', title:'Тренировка чемпионов: путь к победе', src:'yt', url:'https://www.youtube.com/embed/lRKvoKlFwsg', cat:'sport'},
  {id:'v103', title:'Как начать заниматься спортом с нуля', src:'yt', url:'https://www.youtube.com/embed/gC_L9qAHVJ8', cat:'sport'},
  {id:'v104', title:'История Конора Макгрегора — путь к вершине', src:'yt', url:'https://www.youtube.com/embed/Unzjd1iABbQ', cat:'sport'},
  {id:'v105', title:'Бег как философия жизни', src:'yt', url:'https://www.youtube.com/embed/8COaMKbNrX0', cat:'sport'},
  {id:'v106', title:'Мотивация для спортзала — будь сильнее', src:'yt', url:'https://www.youtube.com/embed/n8Z_XbdUb_E', cat:'sport'},
  {id:'v107', title:'Как тренируется Криштиану Роналду', src:'yt', url:'https://www.youtube.com/embed/aaEo_NuH1_M', cat:'sport'},
  {id:'v108', title:'Кроссфит: как начать и не бросить', src:'yt', url:'https://www.youtube.com/embed/mC2jPCbMrSo', cat:'sport'},
  {id:'v109', title:'Спортивная мотивация — превзойди себя', src:'yt', url:'https://www.youtube.com/embed/oHg5SJYRHA0', cat:'sport'},
  {id:'v110', title:'Как правильно ставить спортивные цели', src:'yt', url:'https://www.youtube.com/embed/lq85TFDBzB4', cat:'sport'},
  {id:'v111', title:'Железная воля: истории спортсменов', src:'yt', url:'https://www.youtube.com/embed/6Jidkf7RggU', cat:'sport'},
  {id:'v112', title:'Йога для начинающих — энергия на весь день', src:'yt', url:'https://www.youtube.com/embed/v7AYKMP6rOE', cat:'sport'},
  {id:'v113', title:'Как бегать правильно: техника и мотивация', src:'yt', url:'https://www.youtube.com/embed/brFHyOtTwH4', cat:'sport'},
  {id:'v114', title:'Тренировка дома без оборудования', src:'yt', url:'https://www.youtube.com/embed/UBMk30rjy0o', cat:'sport'},
  {id:'v115', title:'Марафон: как подготовиться к первому забегу', src:'yt', url:'https://www.youtube.com/embed/fJn6setwCaU', cat:'sport'},
  {id:'v116', title:'Бокс: дисциплина и характер', src:'yt', url:'https://www.youtube.com/embed/s_osQvkeNRM', cat:'sport'},
  {id:'v117', title:'Как набрать мышечную массу правильно', src:'yt', url:'https://www.youtube.com/embed/ixkQaZXVQjs', cat:'sport'},
  {id:'v118', title:'Плавание: путь от новичка до мастера', src:'yt', url:'https://www.youtube.com/embed/gh5_7MXSXZQ', cat:'sport'},
  {id:'v119', title:'Спортивное питание: основы для всех', src:'yt', url:'https://www.youtube.com/embed/wDDz4Jm6JBc', cat:'sport'},
  {id:'v120', title:'Как восстанавливаться после тренировок', src:'yt', url:'https://www.youtube.com/embed/cfisrXNPtbA', cat:'sport'},

  // === SUCCESS (успех) — v121..v140 ===
  {id:'v121', title:'Секреты успешных людей — что их отличает', src:'yt', url:'https://www.youtube.com/embed/u5CVsCnxyXg', cat:'success'},
  {id:'v122', title:'Как добиться успеха: 10 принципов', src:'yt', url:'https://www.youtube.com/embed/PivWY9wn5ps', cat:'success'},
  {id:'v123', title:'Мышление победителя — психология успеха', src:'yt', url:'https://www.youtube.com/embed/VNGFep6rncY', cat:'success'},
  {id:'v124', title:'История успеха Илона Маска', src:'yt', url:'https://www.youtube.com/embed/8_lfxPI5ObM', cat:'success'},
  {id:'v125', title:'Как ставить цели и достигать их', src:'yt', url:'https://www.youtube.com/embed/L4N1q4RNi9I', cat:'success'},
  {id:'v126', title:'Путь от бедности к богатству', src:'yt', url:'https://www.youtube.com/embed/q5nVqeVhgQE', cat:'success'},
  {id:'v127', title:'Визуализация: как притянуть успех', src:'yt', url:'https://www.youtube.com/embed/1RealFW7UaI', cat:'success'},
  {id:'v128', title:'Как преодолеть неудачи на пути к успеху', src:'yt', url:'https://www.youtube.com/embed/zMhMj_P6fGs', cat:'success'},
  {id:'v129', title:'Законы успеха — что говорит наука', src:'yt', url:'https://www.youtube.com/embed/Y1ct7FG1jOY', cat:'success'},
  {id:'v130', title:'Как найти своё призвание в жизни', src:'yt', url:'https://www.youtube.com/embed/vVsXO9brK7M', cat:'success'},
  {id:'v131', title:'Менталитет миллионера', src:'yt', url:'https://www.youtube.com/embed/IoPGMiSl0pg', cat:'success'},
  {id:'v132', title:'Формула успеха: талант, труд и удача', src:'yt', url:'https://www.youtube.com/embed/3LopI4YeC4I', cat:'success'},
  {id:'v133', title:'Как окружение влияет на твой успех', src:'yt', url:'https://www.youtube.com/embed/Ks-_Mh1QhMc', cat:'success'},
  {id:'v134', title:'Истории людей которые не сдались', src:'yt', url:'https://www.youtube.com/embed/aStr9vkFeKQ', cat:'success'},
  {id:'v135', title:'Как сохранить мотивацию на длинной дистанции', src:'yt', url:'https://www.youtube.com/embed/TJuivFgSWNA', cat:'success'},
  {id:'v136', title:'Стив Джобс: уроки успеха', src:'yt', url:'https://www.youtube.com/embed/UF8uR6Z6KLc', cat:'success'},
  {id:'v137', title:'Как стать лидером в своей области', src:'yt', url:'https://www.youtube.com/embed/j7GhWJtWrmg', cat:'success'},
  {id:'v138', title:'Почему успех приходит к упорным', src:'yt', url:'https://www.youtube.com/embed/H14bBuluwB8', cat:'success'},
  {id:'v139', title:'Как думают успешные предприниматели', src:'yt', url:'https://www.youtube.com/embed/qlzHknJykuY', cat:'success'},
  {id:'v140', title:'Психология достижений — как прокачать мозг', src:'yt', url:'https://www.youtube.com/embed/pN34FNbOKXc', cat:'success'},

  // === CHANGE (перемены) — v141..v160 ===
  {id:'v141', title:'Как изменить свою жизнь за 90 дней', src:'yt', url:'https://www.youtube.com/embed/KZLq0HE7U0E', cat:'change'},
  {id:'v142', title:'Почему перемены — это хорошо', src:'yt', url:'https://www.youtube.com/embed/4p3gNMbEXBo', cat:'change'},
  {id:'v143', title:'Как выйти из зоны комфорта', src:'yt', url:'https://www.youtube.com/embed/RSUykLfEmVA', cat:'change'},
  {id:'v144', title:'Трансформация жизни: реальные истории', src:'yt', url:'https://www.youtube.com/embed/aJHvwsWWoEA', cat:'change'},
  {id:'v145', title:'Как побороть страх перемен', src:'yt', url:'https://www.youtube.com/embed/ZwGEQcFo9RE', cat:'change'},
  {id:'v146', title:'Перезагрузка жизни — начать с чистого листа', src:'yt', url:'https://www.youtube.com/embed/gsYL4PC_hQE', cat:'change'},
  {id:'v147', title:'Как перестать жить на автопилоте', src:'yt', url:'https://www.youtube.com/embed/GBaHPND2QJg', cat:'change'},
  {id:'v148', title:'Изменение мышления меняет реальность', src:'yt', url:'https://www.youtube.com/embed/pIY-oVlFbwA', cat:'change'},
  {id:'v149', title:'Как начать новую жизнь после кризиса', src:'yt', url:'https://www.youtube.com/embed/tbnzAVRZ9Xc', cat:'change'},
  {id:'v150', title:'Маленькие шаги к большим переменам', src:'yt', url:'https://www.youtube.com/embed/_X0mgOOSpLU', cat:'change'},
  {id:'v151', title:'Как отпустить прошлое и двигаться вперёд', src:'yt', url:'https://www.youtube.com/embed/WPPPFqsECz0', cat:'change'},
  {id:'v152', title:'Нейропластичность: мозг можно изменить', src:'yt', url:'https://www.youtube.com/embed/ELpfYCZa87g', cat:'change'},
  {id:'v153', title:'Как сменить профессию и не пожалеть', src:'yt', url:'https://www.youtube.com/embed/1FdJGQ_M3kk', cat:'change'},
  {id:'v154', title:'Принятие решений которые меняют жизнь', src:'yt', url:'https://www.youtube.com/embed/VNKME7VEOOg', cat:'change'},
  {id:'v155', title:'Как развить гибкость мышления', src:'yt', url:'https://www.youtube.com/embed/M_L-TEe02g0', cat:'change'},
  {id:'v156', title:'Саморазвитие: с чего начать путь', src:'yt', url:'https://www.youtube.com/embed/gQDMQVNS4GA', cat:'change'},
  {id:'v157', title:'Как справиться с трудностями и стать сильнее', src:'yt', url:'https://www.youtube.com/embed/v9CL8HGt4sU', cat:'change'},
  {id:'v158', title:'Переосмысление жизни после 30', src:'yt', url:'https://www.youtube.com/embed/psN1DORYYV0', cat:'change'},
  {id:'v159', title:'Как привлечь позитивные перемены', src:'yt', url:'https://www.youtube.com/embed/ljqra3BcqWM', cat:'change'},
  {id:'v160', title:'Твоя жизнь — твой выбор', src:'yt', url:'https://www.youtube.com/embed/bGYs4KS_djg', cat:'change'}
];
